name: Auto Author Assign
description: 'Assign author to pull requests when the pull requests are opened.'
author: 'ashutosham2002'
inputs:
  repo-token:
    description: 'A token for the repository'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'user-plus'
  color: 'red'
