name: Auto Author 

on:
  workflow_call:
    secrets:
      TOKEN_GITHUB:
        description: 'github token'
        required: true

jobs:
  assigned-author:
    name: auto author
    runs-on: ubuntu-latest

    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
        with: 
          repo-token: ${{ secrets.TOKEN_GITHUB }}
          assignees: VishwajitNagulkar