name: Auto Author Assign

permissions:
  pull-requests: write

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: AshutoshAM2002/test_auto_assigned_author/blob/test/action.yml@main    